grid:
  dim: 2
  L: 1.0
  N: 256      

bc:
  type: periodic

time:
  dt: 2.5e-5  
  T: 0.01

physics:
  pde: heat
  params:
    alpha: 1.0

integrator:
  method: rk4_op  

initial_condition:
  type: gaussian   
  center: 0.5      
  sigma: 0.08
  amp: 1.0

diagnostics:
  - mass
  - l2

io:
  outdir: figures